name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo Build
        run: cargo build --release

      - name: Docker Build
        run: docker build -t app:${{ github.sha }} .

      - name: Flyctl Setup
        run: |
          curl -L https://fly.io/install.sh | sh
          flyctl auth login --access-token ${{ secrets.FLY_ACCESS_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          docker tag app:${{ github.sha }} registry.fly.io/rust-charging-station:${{ github.sha }}
          docker push registry.fly.io/rust-charging-station:${{ github.sha }}
          flyctl deploy -i registry.fly.io/rust-charging-station:${{ github.sha }} -e DATABASE_URL=${{ secrets.DATABASE_URL }}
