name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo Build
        run: cargo build --release

      - name: Docker Build
        run: docker build -t ${{ secrets.GCP_PROJECT_ID }}/app:${{ github.sha }} .

      ##- name: Docker Push
      ##  run: docker push ${{ secrets.GCP_PROJECT_ID }}/app:${{ github.sha }}